version: "3"

vars:
  GIT_DIR:
    sh: pwd
  DOCKER: docker run --rm --user $(id -u):$(id -g) -i -w "/doc" -v "{{.GIT_DIR}}":/doc thomasweise/texlive
  CC: xelatex
  DOCUMENTS_DIR: documents
  OUTPUT_DIR: generated

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  all:
    desc: Build resume, CV, and cover letter
    deps:
      - resume
      - coverletter
      - cv

  resume:
    desc: Build resume.pdf
    sources:
      - "{{.DOCUMENTS_DIR}}/resume.tex"
      - "{{.DOCUMENTS_DIR}}/content/*.tex"
    generates:
      - "{{.OUTPUT_DIR}}/resume.pdf"
    cmds:
      - "{{.DOCKER}} {{.CC}} -output-directory={{.DOCUMENTS_DIR}} {{.DOCUMENTS_DIR}}/resume.tex"
      - mv {{.DOCUMENTS_DIR}}/resume.pdf {{.OUTPUT_DIR}}

  coverletter:
    desc: Build coverletter.pdf
    sources:
      - "{{.DOCUMENTS_DIR}}/coverletter.tex"
      - "{{.DOCUMENTS_DIR}}/content/*.tex"
    generates:
      - "{{.OUTPUT_DIR}}/coverletter.pdf"
    cmds:
      - "{{.DOCKER}} {{.CC}} -output-directory={{.DOCUMENTS_DIR}} {{.DOCUMENTS_DIR}}/coverletter.tex"
      - mv {{.DOCUMENTS_DIR}}/coverletter.pdf {{.OUTPUT_DIR}}

  cv:
    desc: Build cv.pdf
    sources:
      - "{{.DOCUMENTS_DIR}}/cv.tex"
      - "{{.DOCUMENTS_DIR}}/content/*.tex"
    generates:
      - "{{.OUTPUT_DIR}}/cv.pdf"
    cmds:
      - "{{.DOCKER}} {{.CC}} -output-directory={{.DOCUMENTS_DIR}} {{.DOCUMENTS_DIR}}/cv.tex"
      - mv {{.DOCUMENTS_DIR}}/cv.pdf {{.OUTPUT_DIR}}

  clean:
    desc: Remove generated PDF and auxiliary files
    cmds:
      - rm -rf {{.OUTPUT_DIR}}/*.pdf {{.DOCUMENTS_DIR}}/*.pdf {{.DOCUMENTS_DIR}}/*.log {{.DOCUMENTS_DIR}}/*.aux
