version: "3"

vars:
  GIT_DIR:
    sh: pwd
  IMAGE_NAME: jshvn-texlive
  DOCKER: docker run --rm --user $(id -u):$(id -g) -i -w "/doc" -v "{{.GIT_DIR}}":/doc {{.IMAGE_NAME}}
  CC: xelatex -interaction=nonstopmode -halt-on-error
  DOCUMENTS_DIR: documents
  OUTPUT_DIR: documents/generated

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  build-image:
    desc: Build the custom LaTeX Docker image
    run: once
    sources:
      - Dockerfile
    status:
      - docker image inspect {{.IMAGE_NAME}} >/dev/null 2>&1
    cmds:
      - docker build -t {{.IMAGE_NAME}} .

  git-info:
    desc: Generate git metadata for gitinfo2 package
    run: once
    sources:
      - .git/HEAD
      - .git/refs/heads/**
    generates:
      - .git/gitHeadInfo.gin
    cmds:
      - ./scripts/generate-git-info.sh
      - cat .git/gitHeadInfo.gin

  all:
    desc: Build resume, CV, and cover letter
    deps:
      - build-image
      - git-info
    cmds:
      - task: resume
      - task: coverletter
      - task: cv

  resume:
    desc: Build resume.pdf
    deps:
      - build-image
      - git-info
    sources:
      - "{{.DOCUMENTS_DIR}}/resume.tex"
      - "{{.DOCUMENTS_DIR}}/content/*.tex"
      - "{{.DOCUMENTS_DIR}}/awesome-cv.cls"
      - ".git/gitHeadInfo.gin"
    generates:
      - "{{.OUTPUT_DIR}}/resume.pdf"
    cmds:
      - "{{.DOCKER}} {{.CC}} -output-directory={{.DOCUMENTS_DIR}} {{.DOCUMENTS_DIR}}/resume.tex"
      - mv {{.DOCUMENTS_DIR}}/resume.pdf {{.OUTPUT_DIR}}

  coverletter:
    desc: Build coverletter.pdf
    deps:
      - build-image
      - git-info
    sources:
      - "{{.DOCUMENTS_DIR}}/coverletter.tex"
      - "{{.DOCUMENTS_DIR}}/content/*.tex"
      - "{{.DOCUMENTS_DIR}}/awesome-cv.cls"
      - ".git/gitHeadInfo.gin"
    generates:
      - "{{.OUTPUT_DIR}}/coverletter.pdf"
    cmds:
      - "{{.DOCKER}} {{.CC}} -output-directory={{.DOCUMENTS_DIR}} {{.DOCUMENTS_DIR}}/coverletter.tex"
      - mv {{.DOCUMENTS_DIR}}/coverletter.pdf {{.OUTPUT_DIR}}

  cv:
    desc: Build cv.pdf
    deps:
      - build-image
      - git-info
    sources:
      - "{{.DOCUMENTS_DIR}}/cv.tex"
      - "{{.DOCUMENTS_DIR}}/content/*.tex"
      - "{{.DOCUMENTS_DIR}}/awesome-cv.cls"
      - ".git/gitHeadInfo.gin"
    generates:
      - "{{.OUTPUT_DIR}}/cv.pdf"
    cmds:
      - "{{.DOCKER}} {{.CC}} -output-directory={{.DOCUMENTS_DIR}} {{.DOCUMENTS_DIR}}/cv.tex"
      - mv {{.DOCUMENTS_DIR}}/cv.pdf {{.OUTPUT_DIR}}

  clean:
    desc: Remove generated PDF and auxiliary files
    cmds:
      - rm -rf {{.OUTPUT_DIR}}/*.pdf {{.DOCUMENTS_DIR}}/*.pdf {{.DOCUMENTS_DIR}}/*.log {{.DOCUMENTS_DIR}}/*.aux {{.DOCUMENTS_DIR}}/*.out
      - rm -f .git/gitHeadInfo.gin
